name: e2_explorer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
#  mqtt_client: ^9.8.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bitsdojo_window: ^0.1.5
  flutter_json_view: ^1.1.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  mqtt5_client: ^4.0.0
  google_fonts: ^5.1.0
  flutter_widget_offset: ^1.1.0
  carbon_icons: ^0.0.1+2
  json_data_explorer: ^0.1.0
  provider: ^6.1.2
  meta: ^1.9.1
  go_router: any
  path_provider: ^2.0.15
  file_picker: any
  shared_preferences: ^2.1.2
  updat: ^1.3.1
  data_table_2: ^2.5.7
  flutter_svg: ^2.0.9
  flutter_highlight: ^0.7.0
  popover: ^0.3.0
  collection: ^1.18.0
  uuid: ^4.4.0
  archive: ^3.4.10
  toastification: ^1.2.1



  # Elliptic Sign & Verify
  pointycastle: ^3.7.4
  basic_utils: ^5.7.0
  crypto: ^3.0.3
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1





dev_dependencies:
  #flutter_test:
   # sdk: flutter

  flutter_lints: ^2.0.1
  very_good_analysis: ^5.0.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/svg/sidenav/
    - assets/icons/svg/
    - assets/icons/png/sidenav/
    - assets/icons/png/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans_Normal.ttf
        - asset: assets/fonts/OpenSans/OpenSans_Italic.ttf


